# Generated by Django 5.1.8 on 2025-06-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the climatological variable', max_length=150, unique=True)),
                ('shortName', models.CharField(help_text='Short_name used by the systems source', max_length=50, unique=True)),
                ('active', models.BooleanField(default=True, help_text='Activate or disactivate the variable')),
                ('unit', models.CharField(default='', help_text='The unit of the variable', max_length=50, null=True)),
            ],
            options={
                'permissions': [('edit_Climvariables', 'Can edit Climatology variables')],
            },
        ),
    ]
