# Generated by Django 5.1.8 on 2025-05-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0012_remove_forecast_source'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='zone',
            name='unique_name_category',
        ),
        migrations.AlterField(
            model_name='zone',
            name='category',
            field=models.CharField(blank=True, choices=[('polygon', 'Plolygone'), ('commune', 'Commune'), ('province', 'Province'), ('region', 'Région'), ('ville', 'Ville')], max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('name', 'category', 'geom'), name='unique_name_category_geom'),
        ),
    ]
