# Generated by Django 5.1.8 on 2025-05-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0013_remove_zone_unique_name_category_alter_zone_category_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='zone',
            name='unique_name_category_geom',
        ),
    ]
