# Generated by Django 5.1.8 on 2025-05-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0028_teststreampage_alter_bulletintemplate_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
