# Generated by Django 5.1.8 on 2025-05-11 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0030_delete_stationtest_alter_bulletintemplate_content_and_more'),
        ('forecast', '0013_remove_zone_unique_name_category_alter_zone_category'),
        ('observation', '0004_alter_station_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du regrouppement de localités', max_length=150)),
                ('stations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observation.station')),
                ('villes', models.ForeignKey(limit_choices_to={'category': 'ville'}, on_delete=django.db.models.deletion.CASCADE, related_name='localites_villes', to='forecast.zone')),
                ('zone', models.ForeignKey(limit_choices_to={'category__in': ['polygon', 'region', 'province']}, on_delete=django.db.models.deletion.CASCADE, related_name='localites_zones', to='forecast.zone')),
            ],
        ),
    ]
