# Generated by Django 5.1.8 on 2025-05-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0031_localites'),
        ('forecast', '0013_remove_zone_unique_name_category_alter_zone_category'),
        ('observation', '0004_alter_station_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localites',
            name='stations',
        ),
        migrations.RemoveField(
            model_name='localites',
            name='villes',
        ),
        migrations.AddField(
            model_name='localites',
            name='stations',
            field=models.ManyToManyField(to='observation.station'),
        ),
        migrations.AddField(
            model_name='localites',
            name='villes',
            field=models.ManyToManyField(limit_choices_to={'category': 'ville'}, to='forecast.zone'),
        ),
    ]
