# Generated by Django 5.1.8 on 2025-05-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0032_remove_localites_stations_remove_localites_villes_and_more'),
        ('forecast', '0013_remove_zone_unique_name_category_alter_zone_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Echeances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du regrouppement des echéances', max_length=150)),
                ('echeances', models.ManyToManyField(to='bulletins.echeance')),
            ],
        ),
        migrations.CreateModel(
            name='Parametres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du regrouppement des paramètres', max_length=150)),
                ('parametres', models.ManyToManyField(to='forecast.variable')),
            ],
        ),
    ]
