# Generated by Django 5.1.8 on 2025-06-01 10:44

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Organisation Name')),
                ('phone', models.CharField(blank=True, help_text='Phone Number', max_length=255, null=True, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254, null=True, verbose_name='Email address')),
                ('address', wagtail.fields.RichTextField(blank=True, help_text='Postal Address', max_length=250, null=True, verbose_name='Postal address')),
                ('country_flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Country Flag')),
                ('favicon', models.ForeignKey(blank=True, help_text='Does not need to be any larger than 200x200 pixels. A 1:1 (square) image ratio is best here - If the image is not square, it will be scaled to a square.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('footer_logo', models.ForeignKey(blank=True, help_text='Logo that appears on the footer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Footer Logo')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Organisation Logo')),
                ('page_not_found_error_image', models.ForeignKey(blank=True, help_text='Image shown on error 404 page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Page not Found Image')),
                ('server_error_image', models.ForeignKey(blank=True, help_text='Image shown on error 500 error page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Server Error Image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
                ('site_logo', models.ForeignKey(blank=True, help_text='Logo that appears on the Site. Should be a whit transparent logo preferably', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo Site')),
            ],
            options={
                'verbose_name': 'Organisation Settings',
            },
        ),
    ]
