# Generated by Django 5.1.8 on 2025-06-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationsetting',
            name='footer_text_site',
            field=models.CharField(blank=True, max_length=455, null=True, verbose_name='Footer site'),
        ),
        migrations.AddField(
            model_name='organisationsetting',
            name='name_site',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System Name'),
        ),
    ]
