# Generated by Django 5.1.8 on 2025-06-01 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0002_organisationsetting_footer_text_site_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationsetting',
            name='footer_image_bulletin',
            field=models.ForeignKey(blank=True, help_text='Logo that appears on the footer of bulletins', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Footer Logo'),
        ),
        migrations.AddField(
            model_name='organisationsetting',
            name='header_image_bulletin',
            field=models.ForeignKey(blank=True, help_text='Logo that appears on the footer of bulletins', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Footer Logo'),
        ),
    ]
