# Generated by Django 5.1.8 on 2025-06-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0003_organisationsetting_footer_image_bulletin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationsetting',
            name='shapefile_zip',
            field=models.FileField(blank=True, help_text='Upload a ZIP file containing .shp, .shx, .dbf, .prj files', null=True, upload_to='shapefiles/', verbose_name='Shapefile (ZIP)'),
        ),
    ]
