# Generated by Django 5.1.8 on 2025-06-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0004_organisationsetting_shapefile_zip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisationsetting',
            options={'permissions': [('edit_setting', 'Can edit settings site')], 'verbose_name': 'Organisation Settings'},
        ),
    ]
