# Generated by Django 5.1.8 on 2025-06-19 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0005_alter_organisationsetting_options'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationsetting',
            name='shapefile_zip',
        ),
        migrations.AddField(
            model_name='organisationsetting',
            name='zip_file',
            field=models.ForeignKey(blank=True, help_text='Shapefile associer à la carte (.zip)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
