# Generated by Django 5.1.8 on 2025-06-19 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0006_remove_organisationsetting_shapefile_zip_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisationsetting',
            old_name='zip_file',
            new_name='shapefile_zip',
        ),
    ]
