# Generated by Django 5.1.8 on 2025-06-13 20:41

import django.core.validators
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom officiel ou organisation du client', max_length=100, unique=True)),
                ('active', models.BooleanField(default=True, help_text='Décocher pour désactiver ce client', verbose_name='Actif')),
                ('email', models.EmailField(help_text='Adresse e-mail principale du client', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Numéro de téléphone fixe', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{6,15}$', 'Entrez un numéro de téléphone valide (min. 6 chiffres).')])),
                ('fax', models.CharField(blank=True, help_text='Numéro de fax', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{6,15}$', 'Entrez un numéro de téléphone valide (min. 6 chiffres).')])),
                ('sms_phone', models.CharField(blank=True, help_text="Numéro GSM pour l'envoi de SMS", max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{6,15}$', 'Entrez un numéro de téléphone valide (min. 6 chiffres).')])),
                ('transmit_mail', models.BooleanField(default=False, verbose_name='Par e-mail')),
                ('transmit_fax', models.BooleanField(default=False, verbose_name='Par fax')),
                ('transmit_sms', models.BooleanField(default=False, verbose_name='Par SMS')),
                ('transmit_ftp', models.BooleanField(default=False, verbose_name='Via FTP')),
                ('transmit_sftp', models.BooleanField(default=False, verbose_name='Via SFTP')),
                ('ftp_host', models.CharField(blank=True, max_length=200, null=True)),
                ('ftp_login', models.CharField(blank=True, max_length=100, null=True)),
                ('ftp_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='dissiminate_name_082d07_idx'), models.Index(fields=['active'], name='dissiminate_active_6866db_idx')],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
