# Generated by Django 5.1.8 on 2025-06-14 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0091_remove_bulletintemplate_clients_delete_client'),
        ('dissiminate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinDessimination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributed_at', models.DateTimeField(auto_now_add=True)),
                ('via_mail', models.BooleanField(default=False)),
                ('via_fax', models.BooleanField(default=False)),
                ('via_sms', models.BooleanField(default=False)),
                ('via_ftp', models.BooleanField(default=False)),
                ('via_sftp', models.BooleanField(default=False)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='bulletins.bulletintemplate')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='dissiminate.client')),
            ],
            options={
                'verbose_name': 'Diffusion du bulletin',
                'verbose_name_plural': 'Diffusions de bulletins',
                'unique_together': {('bulletin', 'client')},
            },
        ),
    ]
