# Generated by Django 5.1.8 on 2025-06-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissiminate', '0002_bulletindessimination'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletindessimination',
            name='active',
            field=models.BooleanField(default=True, help_text="Décochez pour suspendre temporairement l'envoi de ce bulletin à ce client.", verbose_name='Diffusion active'),
        ),
    ]
