# Generated by Django 5.1.8 on 2025-06-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissiminate', '0003_bulletindessimination_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletindessimination',
            name='via_mail',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='transmit_mail',
            field=models.BooleanField(default=True, verbose_name='Par e-mail'),
        ),
    ]
