# Generated by Django 5.1.8 on 2025-06-18 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissiminate', '0005_bulletintransmissionlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletindessimination',
            options={'permissions': [('edit_dessiminate', 'Can edit Diffusion mail')], 'verbose_name': 'Diffusion du bulletin', 'verbose_name_plural': 'Diffusions de bulletins'},
        ),
        migrations.AlterModelOptions(
            name='bulletintransmissionlog',
            options={'ordering': ['-sent_at'], 'permissions': [('edit_logTrans', 'Can edit Log Transmission')]},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'permissions': [('edit_client', 'Can edit Clients')], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
