# Generated by Django 5.1.8 on 2025-06-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissiminate', '0006_alter_bulletindessimination_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ftp_password',
            field=models.CharField(blank=True, help_text='Mot de passe FTP/SFTP', max_length=100, null=True),
        ),
    ]
