# Generated by Django 5.1.8 on 2025-07-06 01:35

import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissiminate', '0007_client_ftp_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du groupe des clients', max_length=150, verbose_name='Nom du groupe')),
                ('clients', models.ManyToManyField(help_text='Nom du groupe des clients', to='dissiminate.client')),
            ],
            options={
                'permissions': [('edit_gclient', 'Can edit Group Clients')],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
