# Generated by Django 5.1.8 on 2025-07-06 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0100_alter_bulletintemplate_content'),
        ('dissiminate', '0008_groupclient'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bulletindessimination',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bulletindessimination',
            name='clients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='dissiminate.groupclient'),
        ),
        migrations.AlterUniqueTogether(
            name='bulletindessimination',
            unique_together={('bulletin', 'clients')},
        ),
    ]
