# Generated by Django 5.1.8 on 2025-07-06 10:53

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissiminate', '0009_alter_bulletindessimination_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletindessimination',
            name='html_content',
            field=models.BooleanField(default=False, help_text='Envoyer le bulletin en format html dans le mail', verbose_name='Contenu Html'),
        ),
        migrations.AddField(
            model_name='bulletindessimination',
            name='message_body',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Contenu du message'),
        ),
        migrations.AddField(
            model_name='bulletindessimination',
            name='pdf_content',
            field=models.BooleanField(default=True, help_text='Envoyer le bulletin en format pdf en pièce jointe', verbose_name='Contenu Pdf'),
        ),
        migrations.AlterField(
            model_name='bulletindessimination',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client dans le mail principal.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='dissiminate.client', verbose_name='Client principal'),
        ),
        migrations.AlterField(
            model_name='bulletindessimination',
            name='clients',
            field=models.ForeignKey(blank=True, help_text='Groupe de clients en CCi (mail).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='dissiminate.groupclient', verbose_name='Groupe de Clients'),
        ),
    ]
