# Generated by Django 5.1.8 on 2025-07-06 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissiminate', '0010_bulletindessimination_html_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulletintransmissionlog',
            old_name='email',
            new_name='emails',
        ),
        migrations.AddField(
            model_name='bulletintransmissionlog',
            name='clients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dissiminate.groupclient'),
        ),
        migrations.AlterField(
            model_name='bulletintransmissionlog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dissiminate.client'),
        ),
    ]
