# Generated by Django 4.2.20 on 2025-04-19 18:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecast', '0002_zone_zone_unique_name_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BulletinTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='bulletin', max_length=100, verbose_name='Nom du bulletin')),
                ('bulletin_title', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('established_date', models.DateField()),
                ('header_text', models.TextField(blank=True, null=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='bulletin_headers/')),
                ('footer_text', models.TextField(blank=True, null=True)),
                ('footer_image', models.ImageField(blank=True, null=True, upload_to='bulletin_footers/')),
                ('content', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock(editor='default')), ('text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Section Title', max_length=100, verbose_name='Section Title')), ('text', wagtail.blocks.RichTextBlock(help_text='Section description', verbose_name='Section Text'))])), ('textImage', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Section Title', max_length=100)), ('text', wagtail.blocks.RichTextBlock(editor='default', help_text='Section description')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Choose an image', required=False))])), ('table', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'colHeaders': False, 'rowHeaders': False}))])), ('forecast_table', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True))]))])),
                ('body', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock(editor='default')), ('text_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Section Title', max_length=100, verbose_name='Section Title')), ('text', wagtail.blocks.RichTextBlock(help_text='Section description', verbose_name='Section Text'))])), ('textImage', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Section Title', max_length=100)), ('text', wagtail.blocks.RichTextBlock(editor='default', help_text='Section description')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Choose an image', required=False))]))])),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('faxe', models.CharField(blank=True, max_length=15, null=True)),
                ('sms_phone', models.CharField(blank=True, help_text="Numéro de téléphone GSM pour l'envoi de SMS", max_length=15, null=True)),
                ('active', models.BooleanField(default=True)),
                ('transmit_mail', models.BooleanField(default=False)),
                ('transmit_faxe', models.BooleanField(default=False)),
                ('transmit_sms', models.BooleanField(default=False)),
                ('transmit_ftp', models.BooleanField(default=False)),
                ('transmit_sftp', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('echeance', models.IntegerField(unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BulletinZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(null=True)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.bulletintemplate')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.zone')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='bulletintemplate',
            name='clients',
            field=models.ManyToManyField(related_name='bulletins', to='bulletins.client', verbose_name='Clients associés au bulletin'),
        ),
        migrations.AddField(
            model_name='bulletintemplate',
            name='echeances',
            field=models.ManyToManyField(related_name='bulletins', to='bulletins.echeance', verbose_name='Echéances associés au bulletin'),
        ),
        migrations.AddField(
            model_name='bulletintemplate',
            name='parameters',
            field=models.ManyToManyField(related_name='bulletins', through='bulletins.BulletinParameter', to='forecast.variable', verbose_name='Paramètres associés au bulletin'),
        ),
        migrations.AddField(
            model_name='bulletintemplate',
            name='zone',
            field=models.ManyToManyField(related_name='bulletins', through='bulletins.BulletinZone', to='forecast.zone', verbose_name='Zones associées au bulletin'),
        ),
        migrations.AddField(
            model_name='bulletinparameter',
            name='bulletin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.bulletintemplate'),
        ),
        migrations.AddField(
            model_name='bulletinparameter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.variable'),
        ),
    ]
