# Generated by Django 4.2.20 on 2025-04-19 19:18

from django.db import migrations
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletintemplate',
            name='content',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock(editor='default')), ('text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Section Title', max_length=100, verbose_name='Section Title')), ('text', wagtail.blocks.RichTextBlock(help_text='Section description', verbose_name='Section Text'))])), ('textImage', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Section Title', max_length=100)), ('text', wagtail.blocks.RichTextBlock(editor='default', help_text='Section description')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Choose an image', required=False))])), ('table', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'colHeaders': False, 'rowHeaders': False}))]))]),
        ),
    ]
