# Generated by Django 4.2.20 on 2025-04-22 22:23

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0008_alter_bulletintemplate_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletintemplate',
            name='body',
        ),
        migrations.RemoveField(
            model_name='bulletintemplate',
            name='echeances',
        ),
        migrations.RemoveField(
            model_name='bulletintemplate',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='bulletintemplate',
            name='zone',
        ),
        migrations.AlterField(
            model_name='bulletintemplate',
            name='content',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock(editor='default')), ('text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Section Title', max_length=100, verbose_name='Section Title')), ('text', wagtail.blocks.RichTextBlock(help_text='Section description', verbose_name='Section Text'))])), ('textImage', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Section Title', max_length=100)), ('text', wagtail.blocks.RichTextBlock(editor='default', help_text='Section description')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Choose an image', required=False))])), ('forecast_table', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False))]))]),
        ),
    ]
