# Generated by Django 4.2.20 on 2025-04-22 22:38

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0005_alter_forecast_echeance'),
        ('bulletins', '0009_remove_bulletintemplate_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletintemplate',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock(editor='default')), ('text_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Section Title', max_length=100, verbose_name='Section Title')), ('text', wagtail.blocks.RichTextBlock(help_text='Section description', verbose_name='Section Text'))])), ('textImage', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Section Title', max_length=100)), ('text', wagtail.blocks.RichTextBlock(editor='default', help_text='Section description')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Choose an image', required=False))]))], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bulletintemplate',
            name='echeances',
            field=models.ManyToManyField(related_name='bulletins', to='bulletins.echeance', verbose_name='Echéances associés au bulletin'),
        ),
        migrations.AddField(
            model_name='bulletintemplate',
            name='parameters',
            field=models.ManyToManyField(related_name='bulletins', through='bulletins.BulletinParameter', to='forecast.variable', verbose_name='Paramètres associés au bulletin'),
        ),
        migrations.AddField(
            model_name='bulletintemplate',
            name='zone',
            field=models.ManyToManyField(related_name='bulletins', through='bulletins.BulletinZone', to='forecast.zone', verbose_name='Zones associées au bulletin'),
        ),
    ]
