# Generated by Django 5.1.8 on 2025-04-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0011_alter_bulletintemplate_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletintemplate',
            name='footer_text',
        ),
        migrations.RemoveField(
            model_name='bulletintemplate',
            name='header_text',
        ),
    ]
