# Generated by Django 5.1.8 on 2025-04-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0012_remove_bulletintemplate_footer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletintemplate',
            name='footer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulletintemplate',
            name='header_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
