# Generated by Django 5.1.8 on 2025-05-03 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0013_bulletintemplate_footer_text_and_more'),
        ('forecast', '0010_remove_observation_forecast_ptr_delete_station_and_more'),
        ('observation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneStationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_zones', to='observation.station')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_stations', to='forecast.zone')),
            ],
            options={
                'unique_together': {('zone', 'station')},
            },
        ),
    ]
