# Generated by Django 5.1.8 on 2025-05-03 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0014_zonestationlink'),
        ('forecast', '0010_remove_observation_forecast_ptr_delete_station_and_more'),
        ('observation', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zonestationlink',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='zonestationlink',
            name='station',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zone_link', to='observation.station'),
        ),
        migrations.AlterField(
            model_name='zonestationlink',
            name='zone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='station_link', to='forecast.zone'),
        ),
    ]
