# Generated by Django 5.1.8 on 2025-05-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0015_alter_zonestationlink_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echeance',
            name='echeance',
            field=models.CharField(unique=True),
        ),
    ]
