# Generated by Django 5.1.8 on 2025-05-04 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0016_alter_echeance_echeance'),
        ('forecast', '0010_remove_observation_forecast_ptr_delete_station_and_more'),
        ('observation', '0004_alter_station_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinHeuresObs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(null=True)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.bulletintemplate')),
                ('heure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.echeance')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='bulletintemplate',
            name='heures',
            field=models.ManyToManyField(related_name='obsHeureBulletins', through='bulletins.BulletinHeuresObs', to='bulletins.echeance', verbose_name="Echéances d'Observation associés au bulletin"),
        ),
        migrations.CreateModel(
            name='BulletinParameterObs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(null=True)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.bulletintemplate')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.variable')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='bulletintemplate',
            name='obs_parameters',
            field=models.ManyToManyField(related_name='obsParamBulletins', through='bulletins.BulletinParameterObs', to='forecast.variable', verbose_name="Paramètres d'Observation associés au bulletin"),
        ),
        migrations.CreateModel(
            name='BulletinStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(null=True)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.bulletintemplate')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observation.station')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='bulletintemplate',
            name='stations',
            field=models.ManyToManyField(related_name='StationBulletins', through='bulletins.BulletinStation', to='observation.station', verbose_name="Stations d'observation associées au bulletin"),
        ),
    ]
