# Generated by Django 5.1.8 on 2025-05-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0017_bulletinheuresobs_bulletintemplate_heures_and_more'),
        ('forecast', '0010_remove_observation_forecast_ptr_delete_station_and_more'),
        ('observation', '0004_alter_station_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletintemplate',
            name='echeances',
            field=models.ManyToManyField(blank=True, null=True, related_name='bulletins', to='bulletins.echeance', verbose_name='Echéances associés au bulletin'),
        ),
        migrations.AlterField(
            model_name='bulletintemplate',
            name='heures',
            field=models.ManyToManyField(blank=True, null=True, related_name='obsHeureBulletins', through='bulletins.BulletinHeuresObs', to='bulletins.echeance', verbose_name="Echéances d'Observation associés au bulletin"),
        ),
        migrations.AlterField(
            model_name='bulletintemplate',
            name='obs_parameters',
            field=models.ManyToManyField(blank=True, null=True, related_name='obsParamBulletins', through='bulletins.BulletinParameterObs', to='forecast.variable', verbose_name="Paramètres d'Observation associés au bulletin"),
        ),
        migrations.AlterField(
            model_name='bulletintemplate',
            name='parameters',
            field=models.ManyToManyField(blank=True, null=True, related_name='bulletins', through='bulletins.BulletinParameter', to='forecast.variable', verbose_name='Paramètres associés au bulletin'),
        ),
        migrations.AlterField(
            model_name='bulletintemplate',
            name='stations',
            field=models.ManyToManyField(blank=True, null=True, related_name='StationBulletins', through='bulletins.BulletinStation', to='observation.station', verbose_name="Stations d'observation associées au bulletin"),
        ),
        migrations.AlterField(
            model_name='bulletintemplate',
            name='zone',
            field=models.ManyToManyField(blank=True, null=True, related_name='bulletins', through='bulletins.BulletinZone', to='forecast.zone', verbose_name='Zones associées au bulletin'),
        ),
    ]
