# Generated by Django 5.1.8 on 2025-05-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0018_alter_bulletintemplate_echeances_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletintemplate',
            name='established_date',
        ),
    ]
