# Generated by Django 5.1.8 on 2025-05-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0021_bulletintemplate_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletintemplate',
            name='logo',
        ),
        migrations.AlterField(
            model_name='bulletintemplate',
            name='footer_image',
            field=models.ImageField(blank=True, null=True, upload_to='bulletin_footers/'),
        ),
        migrations.AlterField(
            model_name='bulletintemplate',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='bulletin_headers/'),
        ),
    ]
