# Generated by Django 5.1.8 on 2025-05-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0023_alter_bulletintemplate_content'),
        ('chartmet', '0004_alter_mapfcstconfiguration_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletintemplate',
            name='fcst_map',
            field=models.ManyToManyField(blank=True, null=True, related_name='MapFcstBulletins', to='chartmet.mapfcstconfiguration', verbose_name='Carte de prévision associés au bulletin'),
        ),
        migrations.AddField(
            model_name='bulletintemplate',
            name='obs_map',
            field=models.ManyToManyField(blank=True, null=True, related_name='MapObsBulletins', to='chartmet.mapobsconfiguration', verbose_name="Carte d'observation associés au bulletin"),
        ),
    ]
