# Generated by Django 5.1.8 on 2025-05-11 06:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0025_alter_bulletintemplate_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletintemplate',
            name='content',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('text', 4), ('textImage', 8), ('ObsTitleTextImage', 11), ('FcstTitleTextImage', 13), ('forecast_table', 15), ('observation_table', 15), ('ObsTitleTextImage2', 21)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'editor': 'default'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section Title', 'max_length': 100, 'verbose_name': 'Section Title'}), 3: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Section description', 'verbose_name': 'Section Text'}), 4: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section Title', 'max_length': 100}), 6: ('wagtail.blocks.RichTextBlock', (), {'editor': 'default', 'help_text': 'Section description'}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Choose an image', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 5), ('text', 6), ('image', 7)]], {}), 9: ('wagtail.blocks.URLBlock', (), {'help_text': 'External link to where the image can be found and downloaded, the images should be in folder yyyy/mm/dd/obs_map.png', 'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Use default generated image instead of providing a download link', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('title', 5), ('url_img', 9), ('default_img', 10)]], {}), 12: ('wagtail.blocks.URLBlock', (), {'help_text': 'External link to where the image can be found and downloaded, the images should be in folder yyyy/mm/dd/fcst_map.png', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('title', 5), ('url_img', 12), ('default_img', 10)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'required': False}), 15: ('wagtail.blocks.StructBlock', [[('title', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'label': 'Titre', 'required': True}), 17: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texte', 'required': False}), 18: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image', 'required': False}), 19: ('wagtail.blocks.MultipleChoiceBlock', [], {'choices': [], 'label': 'Stations', 'required': False}), 20: ('wagtail.blocks.MultipleChoiceBlock', [], {'choices': [], 'label': 'Heures', 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('titre', 16), ('texte', 17), ('image', 18), ('stations', 19), ('heures', 20)]], {})}),
        ),
    ]
