# Generated by Django 5.1.8 on 2025-05-11 16:07

import bulletins.models
import chartmet.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0029_alter_bulletintemplate_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletintemplate',
            name='echeances',
        ),
        migrations.RemoveField(
            model_name='bulletintemplate',
            name='fcst_map',
        ),
        migrations.RemoveField(
            model_name='bulletintemplate',
            name='heures',
        ),
        migrations.RemoveField(
            model_name='bulletintemplate',
            name='obs_map',
        ),
        migrations.RemoveField(
            model_name='bulletintemplate',
            name='obs_parameters',
        ),
        migrations.RemoveField(
            model_name='bulletintemplate',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='bulletintemplate',
            name='stations',
        ),
        migrations.RemoveField(
            model_name='bulletintemplate',
            name='zone',
        ),
        migrations.AlterField(
            model_name='bulletintemplate',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'})}, verbose_name='Contenu optionnel pour ajouter du texte au dessous'),
        ),
        migrations.AlterField(
            model_name='bulletintemplate',
            name='content',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('ObsTableBlock', 7), ('ObsTitleTextImageBlock', 11)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'editor': 'default'}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.snippets.blocks.SnippetChooserBlock', (bulletins.models.Localites,), {'label': 'Stations', 'required': False}), 4: ('wagtail.snippets.blocks.SnippetChooserBlock', (bulletins.models.Echeances,), {'label': 'Heures', 'required': False}), 5: ('wagtail.snippets.blocks.SnippetChooserBlock', (bulletins.models.Parametres,), {'label': 'Parametres', 'required': False}), 6: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texte', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 2), ('stations', 3), ('heures', 4), ('parametres', 5), ('texte', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Titre de la section', 'max_length': 100}), 9: ('wagtail.snippets.blocks.SnippetChooserBlock', (chartmet.models.MapObsConfiguration,), {'label': 'Carte temps sensible', 'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'help_text': 'External link to where the image can be found and downloaded, the images should be in folder yyyy/mm/dd/obs_map.png', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('title', 8), ('obsmap', 9), ('url_img', 10)]], {})}),
        ),
    ]
