# Generated by Django 5.1.8 on 2025-05-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0030_remove_bulletintemplate_echeances_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletinparameter',
            name='bulletin',
        ),
        migrations.RemoveField(
            model_name='bulletinparameter',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='bulletinparameterobs',
            name='bulletin',
        ),
        migrations.RemoveField(
            model_name='bulletinparameterobs',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='bulletinstation',
            name='bulletin',
        ),
        migrations.RemoveField(
            model_name='bulletinstation',
            name='station',
        ),
        migrations.RemoveField(
            model_name='bulletinzone',
            name='bulletin',
        ),
        migrations.RemoveField(
            model_name='bulletinzone',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='zonestationlink',
            name='station',
        ),
        migrations.RemoveField(
            model_name='zonestationlink',
            name='zone',
        ),
        migrations.DeleteModel(
            name='BulletinHeuresObs',
        ),
        migrations.DeleteModel(
            name='BulletinParameter',
        ),
        migrations.DeleteModel(
            name='BulletinParameterObs',
        ),
        migrations.DeleteModel(
            name='BulletinStation',
        ),
        migrations.DeleteModel(
            name='BulletinZone',
        ),
        migrations.DeleteModel(
            name='ZoneStationLink',
        ),
    ]
