# Generated by Django 5.1.8 on 2025-05-11 19:17

import bulletins.models
import chartmet.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0031_remove_bulletinparameter_bulletin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeance',
            name='end',
            field=models.IntegerField(default=36, help_text='exprimé en nombre d heure', verbose_name='Fin'),
        ),
        migrations.AddField(
            model_name='echeance',
            name='start',
            field=models.IntegerField(default=12, help_text='exprimé en nombre d heures', verbose_name='Début'),
        ),
        migrations.AlterField(
            model_name='bulletintemplate',
            name='content',
            field=wagtail.fields.StreamField([('ObsTableBlock', 5), ('ObsTitleTextImageBlock', 9)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.snippets.blocks.SnippetChooserBlock', (bulletins.models.Localites,), {'label': 'Stations', 'required': False}), 2: ('wagtail.snippets.blocks.SnippetChooserBlock', (bulletins.models.Echeances,), {'label': 'Heures', 'required': False}), 3: ('wagtail.snippets.blocks.SnippetChooserBlock', (bulletins.models.Parametres,), {'label': 'Parametres', 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texte', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('stations', 1), ('heures', 2), ('parametres', 3), ('texte', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Titre de la section', 'max_length': 100}), 7: ('wagtail.snippets.blocks.SnippetChooserBlock', (chartmet.models.MapObsConfiguration,), {'label': 'Carte temps sensible', 'required': False}), 8: ('wagtail.blocks.URLBlock', (), {'help_text': 'External link to where the image can be found and downloaded, the images should be in folder yyyy/mm/dd/obs_map.png', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title', 6), ('stations', 1), ('heures', 2), ('parametres', 3), ('texte', 4), ('obsmap', 7), ('url_img', 8)]], {})}),
        ),
    ]
