# Generated by Django 5.1.8 on 2025-05-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0032_echeance_end_echeance_start_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='echeance',
            constraint=models.UniqueConstraint(fields=('start', 'end'), name='unique_start_end'),
        ),
    ]
