# Generated by Django 5.1.8 on 2025-05-12 06:13

import bulletins.models
import chartmet.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0033_echeance_unique_start_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletintemplate',
            name='content',
            field=wagtail.fields.StreamField([('ObsTableBlock', 6), ('ObsTitleTextImageBlock', 10), ('FcstTableBlock', 13), ('FcstTitleTextImageBlock', 15)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Inclure la période dans le titre', 'required': False}), 2: ('wagtail.snippets.blocks.SnippetChooserBlock', (bulletins.models.Localites,), {'label': 'Stations', 'required': False}), 3: ('wagtail.snippets.blocks.SnippetChooserBlock', (bulletins.models.Echeances,), {'label': 'Heures', 'required': False}), 4: ('wagtail.snippets.blocks.SnippetChooserBlock', (bulletins.models.Parametres,), {'label': 'Parametres', 'required': False}), 5: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texte', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('periode', 1), ('stations', 2), ('heures', 3), ('parametres', 4), ('texte', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Titre de la section', 'max_length': 100}), 8: ('wagtail.snippets.blocks.SnippetChooserBlock', (chartmet.models.MapObsConfiguration,), {'label': 'Carte temps sensible', 'required': False}), 9: ('wagtail.blocks.URLBlock', (), {'help_text': 'External link to where the image can be found and downloaded, the images should be in folder yyyy/mm/dd/obs_map.png', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 7), ('periode', 1), ('stations', 2), ('heures', 3), ('parametres', 4), ('texte', 5), ('obsmap', 8), ('url_img', 9)]], {}), 11: ('wagtail.snippets.blocks.SnippetChooserBlock', (bulletins.models.Localites,), {'label': 'Localités', 'required': False}), 12: ('wagtail.snippets.blocks.SnippetChooserBlock', (bulletins.models.Echeances,), {'label': 'Echeances', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('title', 0), ('periode', 1), ('zones', 11), ('echeances', 12), ('parametres', 4), ('texte', 5)]], {}), 14: ('wagtail.snippets.blocks.SnippetChooserBlock', (chartmet.models.MapFcstConfiguration,), {'label': 'Carte temps sensible', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('title', 7), ('periode', 1), ('zones', 11), ('echeances', 12), ('parametres', 4), ('texte', 5), ('fcstmap', 14), ('url_img', 9)]], {})}),
        ),
    ]
