# Generated by Django 5.1.8 on 2025-05-16 18:11

import bulletins.models
import chartmet.models
import forecast.models
import observation.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0034_alter_bulletintemplate_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletintemplate',
            name='content',
            field=wagtail.fields.StreamField([('ObsTableBlock', 6), ('ObsTitleTextImageBlock', 13), ('FcstTableBlock', 16), ('FcstTitleTextImageBlock', 19), ('ModelTitleTextImageBlock', 23)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Inclure la période dans le titre', 'required': False}), 2: ('wagtail.snippets.blocks.SnippetChooserBlock', (bulletins.models.Localites,), {'label': 'Stations', 'required': False}), 3: ('wagtail.snippets.blocks.SnippetChooserBlock', (bulletins.models.Echeances,), {'label': 'Heures', 'required': False}), 4: ('wagtail.snippets.blocks.SnippetChooserBlock', (bulletins.models.Parametres,), {'label': 'Parametres', 'required': False}), 5: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texte', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('periode', 1), ('stations', 2), ('heures', 3), ('parametres', 4), ('texte', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Titre de la section', 'max_length': 100}), 8: ('wagtail.snippets.blocks.SnippetChooserBlock', (observation.models.Station,), {'label': 'Zone', 'required': False}), 9: ('wagtail.snippets.blocks.SnippetChooserBlock', (bulletins.models.Echeance,), {'label': 'Echéance', 'required': False}), 10: ('wagtail.snippets.blocks.SnippetChooserBlock', (forecast.models.Variable,), {'label': 'Paramètre', 'required': False}), 11: ('wagtail.snippets.blocks.SnippetChooserBlock', (chartmet.models.MapObsConfiguration,), {'label': 'Carte temps sensible', 'required': False}), 12: ('wagtail.blocks.URLBlock', (), {'help_text': 'External link to where the image can be found and downloaded, the images should be in folder yyyy/mm/dd/obs_map.png', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('title', 7), ('periode', 1), ('zone', 8), ('echeance', 9), ('parametre', 10), ('texte', 5), ('obsmap', 11), ('url_img', 12)]], {}), 14: ('wagtail.snippets.blocks.SnippetChooserBlock', (bulletins.models.Localites,), {'label': 'Localités', 'required': False}), 15: ('wagtail.snippets.blocks.SnippetChooserBlock', (bulletins.models.Echeances,), {'label': 'Echeances', 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('title', 0), ('periode', 1), ('zones', 14), ('echeances', 15), ('parametres', 4), ('texte', 5)]], {}), 17: ('wagtail.snippets.blocks.SnippetChooserBlock', (forecast.models.Zone,), {'label': 'Zone', 'required': False}), 18: ('wagtail.snippets.blocks.SnippetChooserBlock', (chartmet.models.MapFcstConfiguration,), {'label': 'Carte temps sensible', 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('title', 7), ('periode', 1), ('zone', 17), ('echeance', 9), ('parametre', 10), ('texte', 5), ('fcstmap', 18), ('url_img', 12)]], {}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('gfs_model', 'GFS 0.25')], 'help_text': 'Modèle numérique du temps', 'label': 'MNT'}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('MSLET', 'MSLP (Eta model reduction)'), ('PRES', 'Surface pressure'), ('GUST', 'Wind speed (gust)'), ('PWAT', 'Precipitable water'), ('VIS', 'Visibility'), ('PRATE', 'Precipitation rate'), ('SFCR', 'Forecast surface roughness'), ('VEG', 'Vegetation'), ('LAND', 'Land-sea mask'), ('TMP', '2 metre temperature'), ('RH', '2 metre relative humidity'), ('RH', 'Relative humidity')], 'help_text': 'Paramètre à projeter sur la carte', 'label': 'Paramètre'}), 22: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('mean', 'Moyenne'), ('sum', 'Cumul'), ('max', 'Maximum'), ('min', 'Minimum'), ('sum', 'Somme')], 'help_text': 'Fonction à appliquer sur le paramètre', 'label': 'Fonction'}), 23: ('wagtail.blocks.StructBlock', [[('title', 7), ('periode', 1), ('zone', 17), ('echeance', 9), ('texte', 5), ('modelmap', 18), ('url_img', 12), ('modele', 20), ('parametre', 21), ('fonction', 22)]], {})}),
        ),
    ]
