# Generated by Django 5.1.8 on 2025-05-17 05:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0036_alter_bulletintemplate_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletintemplate',
            name='footer_text',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulletintemplate',
            name='header_text',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
