# Generated by Django 5.1.8 on 2025-05-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0039_alter_bulletintemplate_content'),
        ('forecast', '0013_remove_zone_unique_name_category_alter_zone_category'),
        ('observation', '0004_alter_station_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localites',
            name='stations',
            field=models.ManyToManyField(blank=True, to='observation.station'),
        ),
        migrations.AlterField(
            model_name='localites',
            name='villes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category': 'ville'}, to='forecast.zone'),
        ),
    ]
