# Generated by Django 5.1.8 on 2025-05-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0050_alter_bulletintemplate_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinStyleConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du style (ex: Style par défaut, Rapport interne...)', max_length=100)),
                ('font_family', models.CharField(choices=[('Arial', 'Arial'), ('Times New Roman', 'Times New Roman'), ('Georgia', 'Georgia'), ('Helvetica', 'Helvetica'), ('Calibri', 'Calibri')], default='Georgia', max_length=50)),
                ('font_size', models.PositiveSmallIntegerField(default=11, help_text='Taille de base du texte (en pt)')),
                ('line_height', models.DecimalField(decimal_places=1, default=1.6, help_text='Interligne', max_digits=3)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Paysage')], default='portrait', max_length=10)),
                ('margin_top', models.DecimalField(decimal_places=2, default=2.5, help_text='Marge haut (cm)', max_digits=4)),
                ('margin_bottom', models.DecimalField(decimal_places=2, default=2.5, help_text='Marge bas (cm)', max_digits=4)),
                ('margin_left', models.DecimalField(decimal_places=2, default=3.0, help_text='Marge gauche (cm)', max_digits=4)),
                ('margin_right', models.DecimalField(decimal_places=2, default=2.0, help_text='Marge droite (cm)', max_digits=4)),
                ('text_color', models.CharField(default='#000000', help_text='Couleur du texte (hex)', max_length=7)),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Couleur de fond (hex)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
