# Generated by Django 5.1.8 on 2025-05-31 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0051_bulletinstyleconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletintemplate',
            name='style_bulletin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bulletins.bulletinstyleconfiguration'),
        ),
    ]
