# Generated by Django 5.1.8 on 2025-05-31 11:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0052_bulletintemplate_style_bulletin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinstyleconfiguration',
            name='background_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Couleur de fond (hex)', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='bulletinstyleconfiguration',
            name='text_color',
            field=colorfield.fields.ColorField(default='#000000', help_text='Couleur du texte (hex)', image_field=None, max_length=25, samples=None),
        ),
    ]
