# Generated by Django 5.1.8 on 2025-05-31 12:07

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0053_alter_bulletinstyleconfiguration_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinstyleconfiguration',
            name='margin_bottom_with_footer',
            field=models.PositiveIntegerField(default=100, help_text='Marge basse avec pied de page (px)'),
        ),
        migrations.AddField(
            model_name='bulletinstyleconfiguration',
            name='margin_top_first_page',
            field=models.PositiveIntegerField(default=150, help_text='Marge haute de la première page (px)'),
        ),
        migrations.AddField(
            model_name='bulletinstyleconfiguration',
            name='page_number_color',
            field=colorfield.fields.ColorField(default='#555555', help_text='Couleur du numéro de page (hex)', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='bulletinstyleconfiguration',
            name='page_number_font_size',
            field=models.PositiveSmallIntegerField(default=9, help_text='Taille du numéro de page (pt)'),
        ),
        migrations.AlterField(
            model_name='bulletinstyleconfiguration',
            name='font_family',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Arial Black', 'Arial Black'), ('Verdana', 'Verdana'), ('Tahoma', 'Tahoma'), ('Trebuchet MS', 'Trebuchet MS'), ('Times New Roman', 'Times New Roman'), ('Georgia', 'Georgia'), ('Garamond', 'Garamond'), ('Palatino Linotype', 'Palatino Linotype'), ('Book Antiqua', 'Book Antiqua'), ('Courier New', 'Courier New'), ('Lucida Console', 'Lucida Console'), ('Calibri', 'Calibri'), ('Cambria', 'Cambria'), ('Helvetica', 'Helvetica'), ('Optima', 'Optima'), ('Century Gothic', 'Century Gothic'), ('Segoe UI', 'Segoe UI'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Source Sans Pro', 'Source Sans Pro')], default='Georgia', max_length=50),
        ),
    ]
