# Generated by Django 5.1.8 on 2025-05-31 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0054_bulletinstyleconfiguration_margin_bottom_with_footer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinstyleconfiguration',
            name='margin_bottom',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Marge bas (cm)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='bulletinstyleconfiguration',
            name='margin_left',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Marge gauche (cm)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='bulletinstyleconfiguration',
            name='margin_right',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Marge droite (cm)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='bulletinstyleconfiguration',
            name='margin_top',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Marge haut (cm)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='bulletintemplate',
            name='style_bulletin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bulletins.bulletinstyleconfiguration'),
        ),
    ]
