# Generated by Django 5.1.8 on 2025-05-31 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0055_alter_bulletinstyleconfiguration_margin_bottom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletintemplate',
            name='style_bulletin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulletins.bulletinstyleconfiguration'),
        ),
    ]
