# Generated by Django 5.1.8 on 2025-06-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0058_bulletinstyleconfiguration_block_forecast_table_margin_top_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinstyleconfiguration',
            name='twoColumns',
            field=models.BooleanField(default=False, help_text='Affichage en deux colonnes'),
        ),
    ]
