# Generated by Django 5.1.8 on 2025-06-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0059_bulletinstyleconfiguration_twocolumns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletintemplate',
            name='two_columns',
        ),
    ]
