# Generated by Django 5.1.8 on 2025-06-01 13:03

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0060_remove_bulletintemplate_two_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinstyleconfiguration',
            name='footer_background_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Couleur de fond (hex)', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='bulletinstyleconfiguration',
            name='footer_font_family',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Arial Black', 'Arial Black'), ('Verdana', 'Verdana'), ('Tahoma', 'Tahoma'), ('Trebuchet MS', 'Trebuchet MS'), ('Times New Roman', 'Times New Roman'), ('Georgia', 'Georgia'), ('Garamond', 'Garamond'), ('Palatino Linotype', 'Palatino Linotype'), ('Book Antiqua', 'Book Antiqua'), ('Courier New', 'Courier New'), ('Lucida Console', 'Lucida Console'), ('Calibri', 'Calibri'), ('Cambria', 'Cambria'), ('Helvetica', 'Helvetica'), ('Optima', 'Optima'), ('Century Gothic', 'Century Gothic'), ('Segoe UI', 'Segoe UI'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Source Sans Pro', 'Source Sans Pro')], default='Georgia', max_length=50),
        ),
        migrations.AddField(
            model_name='bulletinstyleconfiguration',
            name='footer_font_size',
            field=models.PositiveSmallIntegerField(default=12, help_text='Taille de base du texte (pt)'),
        ),
        migrations.AddField(
            model_name='bulletinstyleconfiguration',
            name='footer_line_height',
            field=models.DecimalField(decimal_places=1, default=1.6, help_text='Interligne', max_digits=3),
        ),
        migrations.AddField(
            model_name='bulletinstyleconfiguration',
            name='footer_text_align',
            field=models.CharField(choices=[('left', 'Gauche'), ('right', 'Droite'), ('center', 'Centre')], default='left', max_length=50),
        ),
        migrations.AddField(
            model_name='bulletinstyleconfiguration',
            name='footer_text_color',
            field=colorfield.fields.ColorField(default='#000000', help_text='Couleur du texte (hex)', image_field=None, max_length=25, samples=None),
        ),
    ]
