# Generated by Django 5.1.8 on 2025-06-01 15:57

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0061_bulletinstyleconfiguration_footer_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinstyleconfiguration',
            name='border_color',
            field=colorfield.fields.ColorField(default='#000000', help_text='Couleur de bordure', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='bulletinstyleconfiguration',
            name='border_padding',
            field=models.PositiveIntegerField(default=5, help_text='Padding intérieur (px)'),
        ),
        migrations.AddField(
            model_name='bulletinstyleconfiguration',
            name='border_style',
            field=models.CharField(choices=[('solid', 'Solid'), ('dashed', 'Dashed'), ('dotted', 'Dotted'), ('double', 'Double'), ('none', 'None')], default='double', help_text='Style de bordure CSS', max_length=10),
        ),
        migrations.AddField(
            model_name='bulletinstyleconfiguration',
            name='border_width',
            field=models.PositiveIntegerField(default=6, help_text='Épaisseur de la bordure (px)'),
        ),
        migrations.AddField(
            model_name='bulletinstyleconfiguration',
            name='bordures',
            field=models.BooleanField(default=False, help_text='Bordures de la page'),
        ),
    ]
