# Generated by Django 5.1.8 on 2025-06-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bulletins', '0062_bulletinstyleconfiguration_border_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletintemplate',
            name='role',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
