# Generated by Django 5.1.8 on 2025-06-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bulletins', '0063_bulletintemplate_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletintemplate',
            name='role',
            field=models.ManyToManyField(blank=True, help_text="Groupes d'utilisateurs autorisés à accéder et gérer ce modèle de bulletin.", to='auth.group', verbose_name='Groupes autorisés'),
        ),
    ]
