# Generated by Django 5.1.8 on 2025-06-10 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0072_parametres_echeances_alter_bulletintemplate_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametres',
            name='echeances',
        ),
    ]
