# Generated by Django 5.1.8 on 2025-06-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0087_bulletinstyleconfiguration_figcaption_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulletinstyleconfiguration',
            old_name='figcaption_width',
            new_name='figcaption_align',
        ),
    ]
