# Generated by Django 5.1.8 on 2025-06-13 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0089_alter_bulletinstyleconfiguration_font_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletintemplate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bulletintemplate',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='bulletins/pdf/'),
        ),
    ]
