# Generated by Django 5.1.8 on 2025-06-13 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0090_bulletintemplate_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletintemplate',
            name='clients',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
