# Generated by Django 5.1.8 on 2025-06-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0093_alter_bulletintemplate_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletinstyleconfiguration',
            options={'permissions': [('edit_style_bulletin', 'Can edit style bulletin')]},
        ),
        migrations.AlterModelOptions(
            name='bulletintemplate',
            options={'permissions': [('edit_bulletin', 'Can edit Bulletins')], 'verbose_name': 'Template de Bulletin', 'verbose_name_plural': 'Templates de Bulletin'},
        ),
        migrations.AlterModelOptions(
            name='echeance',
            options={'permissions': [('edit_echeance', 'Can edit Echeance')]},
        ),
        migrations.AlterModelOptions(
            name='echeances',
            options={'permissions': [('edit_groupEcheance', 'Can edit Observation')]},
        ),
        migrations.AlterModelOptions(
            name='localites',
            options={'permissions': [('edit_localites', 'Can edit Localites')]},
        ),
        migrations.AlterModelOptions(
            name='parametres',
            options={'permissions': [('edit_groupParameters', 'Can edit group of parameters')]},
        ),
    ]
