# Generated by Django 5.1.8 on 2025-06-20 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0097_alter_bulletintemplate_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletintemplate',
            options={'permissions': [('edit_bulletin', 'Can edit Bulletins'), ('generate_bulletin', 'Can genarate Bulletins')], 'verbose_name': 'Template de Bulletin', 'verbose_name_plural': 'Templates de Bulletin'},
        ),
    ]
