# Generated by Django 5.1.8 on 2025-07-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0100_alter_bulletintemplate_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletintemplate',
            name='html_file',
            field=models.FileField(blank=True, upload_to='bulletins/html/'),
        ),
    ]
