# Generated by Django 5.1.8 on 2025-05-02 23:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecast', '0010_remove_observation_forecast_ptr_delete_station_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('wigos_id', models.CharField(max_length=50, verbose_name='Wigos ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'permissions': [('edit_station', 'Can edit stations')],
                'constraints': [models.UniqueConstraint(fields=('name', 'wigos_id'), name='unique_name_wigos_id')],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.CharField()),
                ('observation', wagtail.fields.RichTextField(blank=True, null=True)),
                ('parametre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.variable')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observation.station')),
            ],
            options={
                'permissions': [('edit_observation', 'Can edit Observation')],
            },
        ),
    ]
