# Generated by Django 5.1.8 on 2025-05-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='elevation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
