# Generated by Django 5.1.8 on 2025-05-03 17:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0002_station_elevation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
