# Generated by Django 5.1.8 on 2025-05-04 09:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0003_alter_station_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
