# Generated by Django 5.1.8 on 2025-05-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0004_alter_station_geom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['name'], 'permissions': [('edit_station', 'Can edit stations')]},
        ),
    ]
