# Generated by Django 5.1.8 on 2025-06-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0014_remove_forecast_unique_attributs_and_more'),
        ('observation', '0005_alter_station_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(fields=('station', 'date', 'heure', 'parametre'), name='unique_attributs_obs'),
        ),
    ]
