# Generated by Django 5.1.8 on 2025-06-17 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0006_observation_unique_attributs_obs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVImportForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decade', models.IntegerField(help_text='Décade (1-3 pour les 10 premiers, 11-20, 21-31 jours du mois)')),
                ('month', models.IntegerField(help_text='Mois (1-12)')),
                ('year', models.IntegerField(help_text='Année')),
                ('source', models.CharField(help_text='Source des données', max_length=255)),
                ('csv_file', models.FileField(help_text='Fichier CSV contenant: lat, lon, value, parameter, source (optionnel), name (optionnel)', upload_to='csv_imports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Import CSV Climat',
                'verbose_name_plural': 'Imports CSV Climat',
            },
        ),
        migrations.CreateModel(
            name='ClimatDecades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('decade', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('parameter', models.CharField(max_length=255)),
                ('value', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'climat.decades',
                'unique_together': {('lon', 'lat', 'decade', 'month', 'year', 'parameter', 'source')},
            },
        ),
    ]
