# Generated by Django 5.1.8 on 2025-06-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0007_csvimportform_climatdecades'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='climatdecades',
            table=None,
        ),
    ]
