# Generated by Django 5.1.8 on 2025-06-17 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0008_alter_climatdecades_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climatdecades',
            name='name',
        ),
        migrations.AddField(
            model_name='climatdecades',
            name='station',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='csvimportform',
            name='csv_file',
            field=models.FileField(help_text='Fichier CSV contenant: lat, lon, value, parameter, station (optionnel)', upload_to='csv_imports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
    ]
