# Generated by Django 5.1.8 on 2025-06-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0009_remove_climatdecades_name_climatdecades_station_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climatdecades',
            options={'permissions': [('edit_climdata', 'Can edit Clim Data')]},
        ),
        migrations.AlterModelOptions(
            name='csvimportform',
            options={'permissions': [('edit_csvimport', 'Can Import CSV decade')], 'verbose_name': 'Import CSV Climat', 'verbose_name_plural': 'Imports CSV Climat'},
        ),
    ]
