# Generated by Django 5.1.8 on 2025-07-06 00:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0011_station_latitude_station_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVImportMois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='Mois (1-12)')),
                ('year', models.IntegerField(help_text='Année')),
                ('source', models.CharField(help_text='Source des données', max_length=255)),
                ('csv_file', models.FileField(help_text='Fichier CSV contenant les données', upload_to='csv_imports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Import CSV Climat Mensuel',
                'verbose_name_plural': 'Imports CSV Climat Mensuel',
            },
        ),
        migrations.AlterModelOptions(
            name='csvimportform',
            options={'verbose_name': 'Import CSV Climat Décades', 'verbose_name_plural': 'Imports CSV Climat Décades'},
        ),
        migrations.AlterField(
            model_name='csvimportform',
            name='csv_file',
            field=models.FileField(help_text='Fichier CSV contenant les données', upload_to='csv_imports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
        migrations.CreateModel(
            name='ClimatMois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(blank=True, max_length=255, null=True)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('parameter', models.CharField(max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('value', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'permissions': [('edit_climdata', 'Can edit Clim Data')],
                'unique_together': {('lon', 'lat', 'month', 'year', 'parameter', 'source')},
            },
        ),
    ]
