# Generated by Django 5.1.8 on 2025-06-19 12:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VigimetProvinceAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_id', models.CharField(max_length=100)),
                ('province_name', models.CharField(max_length=255)),
                ('forecast_date', models.DateField()),
                ('param', models.CharField(max_length=50)),
                ('details', models.JSONField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '"gfs_model"."vigimet_provinces_auto"',
                'abstract': False,
                'unique_together': {('province_id', 'forecast_date', 'param')},
            },
        ),
        migrations.CreateModel(
            name='VigimetProvinceProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_id', models.CharField(max_length=100)),
                ('province_name', models.CharField(max_length=255)),
                ('forecast_date', models.DateField()),
                ('param', models.CharField(max_length=50)),
                ('details', models.JSONField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '"gfs_model"."vigimet_provinces_prod"',
                'abstract': False,
                'unique_together': {('province_id', 'forecast_date', 'param')},
            },
        ),
    ]
