# Generated by Django 5.1.8 on 2025-06-20 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vigilance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vigimetprovinceauto',
            options={'permissions': [('edit_vigilance', 'Can edit vigilance'), ('view_vigilance', 'Can display vigilance')]},
        ),
        migrations.AlterModelOptions(
            name='vigimetprovinceprod',
            options={'permissions': [('edit_vigilance', 'Can edit vigilance'), ('view_vigilance', 'Can display vigilance')]},
        ),
    ]
