# Generated by Django 5.1.8 on 2025-06-02 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0064_userservicerole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userservicerole',
            name='service',
        ),
        migrations.AlterField(
            model_name='userservicerole',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userservicerole',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, to='bulletins.service'),
        ),
    ]
