# Generated by Django 5.1.8 on 2025-06-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0065_remove_userservicerole_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservicerole',
            name='service',
            field=models.ManyToManyField(blank=True, to='bulletins.service'),
        ),
    ]
