# Generated by Django 5.1.8 on 2025-06-02 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0066_alter_userservicerole_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userservicerole',
            name='service',
        ),
        migrations.AddField(
            model_name='userservicerole',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulletins.service'),
        ),
    ]
