# Generated by Django 5.1.8 on 2025-06-02 19:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0067_remove_userservicerole_service_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userservicerole',
            unique_together={('user', 'service')},
        ),
    ]
