# Generated by Django 5.1.8 on 2025-06-02 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bulletins', '0068_alter_userservicerole_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletintemplate',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
