# Generated by Django 5.1.8 on 2025-06-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bulletins', '0069_bulletintemplate_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userservicerole',
            name='service',
        ),
        migrations.RemoveField(
            model_name='bulletintemplate',
            name='service',
        ),
        migrations.AlterUniqueTogether(
            name='userservicerole',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userservicerole',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bulletintemplate',
            name='group',
        ),
        migrations.AddField(
            model_name='bulletintemplate',
            name='role',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='UserServiceRole',
        ),
    ]
