# Generated by Django 4.2.20 on 2025-04-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the meteorological variable', max_length=150, unique=True)),
                ('shortName', models.CharField(help_text='Short_name used by the systems source', max_length=50, unique=True)),
                ('active', models.BooleanField(default=True, help_text='Activate or disactivate the variable')),
                ('unit', models.CharField(default='', help_text='The unit of the variable', max_length=50, null=True)),
                ('category', models.CharField(choices=[('class', 'Classes'), ('value', 'Valeures continues')], default='class', help_text='The variable should be displayed in classes or in a continuous values', max_length=5)),
            ],
            options={
                'permissions': [('edit_variables', 'Can edit variables')],
            },
        ),
    ]
