# Generated by Django 4.2.20 on 2025-04-21 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_zone_zone_unique_name_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('echeance', models.IntegerField()),
                ('prevision', models.CharField(blank=True, null=True)),
                ('parametre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.variable')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.zone')),
            ],
            options={
                'permissions': [('edit_forecast', 'Can edit Forecast')],
            },
        ),
        migrations.AddConstraint(
            model_name='forecast',
            constraint=models.UniqueConstraint(fields=('zone', 'date', 'echeance', 'parametre'), name='unique_attributs'),
        ),
    ]
