# Generated by Django 4.2.20 on 2025-04-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_forecast_forecast_unique_attributs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='echeance',
            field=models.CharField(),
        ),
    ]
