# Generated by Django 4.2.20 on 2025-04-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0004_alter_forecast_echeance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='echeance',
            field=models.IntegerField(),
        ),
    ]
