# Generated by Django 4.2.20 on 2025-04-24 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0005_alter_forecast_echeance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'permissions': [('edit_zone', 'Can edit variables')]},
        ),
    ]
