# Generated by Django 5.1.8 on 2025-04-28 19:18

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_alter_zone_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('forecast_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forecast.forecast')),
                ('observations', wagtail.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'permissions': [('edit_observation', 'Can edit Observation')],
            },
            bases=('forecast.forecast',),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='prevision',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('wigos_id', models.CharField(max_length=50, verbose_name='Wigos ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'permissions': [('edit_station', 'Can edit stations')],
                'constraints': [models.UniqueConstraint(fields=('name', 'wigos_id'), name='unique_name_wigos_id')],
            },
        ),
    ]
