# Generated by Django 5.1.8 on 2025-04-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0007_observation_alter_forecast_prevision_station'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Station',
        ),
    ]
