# Generated by Django 5.1.8 on 2025-04-28 19:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0008_delete_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('wigos_id', models.CharField(max_length=50, verbose_name='Wigos ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'permissions': [('edit_station', 'Can edit stations')],
                'constraints': [models.UniqueConstraint(fields=('name', 'wigos_id'), name='unique_name_wigos_id')],
            },
        ),
    ]
