# Generated by Django 5.1.8 on 2025-05-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0009_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='forecast_ptr',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.AlterField(
            model_name='forecast',
            name='echeance',
            field=models.CharField(),
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
    ]
