# Generated by Django 5.1.8 on 2025-05-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0010_remove_observation_forecast_ptr_delete_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='source',
            field=models.CharField(default='yp'),
        ),
    ]
