# Generated by Django 5.1.8 on 2025-05-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0011_forecast_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='source',
        ),
    ]
