# Generated by Django 5.1.8 on 2025-06-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0013_remove_zone_unique_name_category_alter_zone_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='forecast',
            name='unique_attributs',
        ),
        migrations.AddConstraint(
            model_name='forecast',
            constraint=models.UniqueConstraint(fields=('zone', 'date', 'echeance', 'parametre'), name='unique_attributs_fcst'),
        ),
    ]
