# Generated by Django 5.1.8 on 2025-06-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0015_alter_variable_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='category',
            field=models.CharField(choices=[('class', 'Classes'), ('value', 'Valeurs continues'), ('text', 'Texte')], default='class', help_text='The variable should be displayed in classes or in a continuous values', max_length=5),
        ),
    ]
