# Generated by Django 5.1.8 on 2025-06-10 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0016_alter_variable_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={'ordering': ['name'], 'permissions': [('edit_variables', 'Can edit variables')]},
        ),
    ]
