# Generated by Django 5.1.8 on 2025-06-10 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0017_alter_variable_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['name'], 'permissions': [('edit_zone', 'Can edit variables')]},
        ),
    ]
