# Generated by Django 5.1.8 on 2025-06-18 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0018_alter_zone_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['name'], 'permissions': [('edit_zone', 'Can edit zones')]},
        ),
    ]
