# Generated by Django 5.1.8 on 2025-05-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapobsconfiguration',
            name='name',
            field=models.CharField(default='Carte par defaut', max_length=100),
        ),
    ]
