# Generated by Django 5.1.8 on 2025-05-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0002_alter_mapobsconfiguration_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapfcstconfiguration',
            name='name',
            field=models.CharField(default='Carte par defaut', max_length=100),
        ),
    ]
