# Generated by Django 5.1.8 on 2025-05-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0003_alter_mapfcstconfiguration_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapfcstconfiguration',
            name='name',
            field=models.CharField(default='Carte par defaut', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mapobsconfiguration',
            name='name',
            field=models.CharField(default='Carte par defaut', max_length=100, unique=True),
        ),
    ]
