# Generated by Django 5.1.8 on 2025-05-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0006_mapmodelconfiguration_show_color_fill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapmodelconfiguration',
            name='cmap',
            field=models.CharField(choices=[('viridis', 'viridis : uniforme'), ('plasma', 'plasma : chaud'), ('inferno', 'inferno : lumineux'), ('magma', 'magma : doux'), ('cividis', 'cividis : daltoniens'), ('Blues', 'Blues : bleu foncé'), ('BuGn', 'BuGn : bleu-vert'), ('Oranges', 'Oranges : orange'), ('Purples', 'Purples : violet'), ('coolwarm', 'coolwarm : bleu-rouge'), ('RdBu', 'RdBu : rouge-bleu'), ('seismic', 'seismic : extrêmes'), ('hsv', 'hsv : arc-en-ciel'), ('twilight', 'twilight : cyclique'), ('twilight_shifted', 'twilight_shifted : cyclique 2'), ('Set1', 'Set1 : 10 couleurs'), ('Set2', 'Set2 : 8 couleurs'), ('Set3', 'Set3 : 12 couleurs'), ('Pastel1', 'Pastel1 : pastel'), ('Paired', 'Paired : en paire'), ('gray', 'gray : niveaux gris'), ('spring', 'spring : vive'), ('summer', 'summer : vert-jaune'), ('autumn', 'autumn : orange-rouge'), ('winter', 'winter : bleu-vert')], default='viridis', help_text='Palette de couleur. Consultez la <a href="https://matplotlib.org/stable/gallery/color/colormap_reference.html" target="_blank" rel="noopener noreferrer">référence des palettes matplotlib</a>.', verbose_name='Palette de couleurs'),
        ),
    ]
