# Generated by Django 5.1.8 on 2025-05-14 19:32

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0007_alter_mapmodelconfiguration_cmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='contour_edgecolor',
            field=colorfield.fields.ColorField(default='#000000', help_text='Couleur des isolignes.', image_field=None, max_length=25, samples=None, verbose_name='Couleur des isolignes'),
        ),
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='contour_labelsize',
            field=models.PositiveIntegerField(default=5, help_text='Taille de police des étiquettes (3 à 20).', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)], verbose_name='Taille de la police des étiquettes'),
        ),
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='contour_linewidths',
            field=models.FloatField(default=0.8, help_text='Épaisseur des isolignes (0.1 à 3.0)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(3.0)], verbose_name='Épaisseur des isolignes'),
        ),
        migrations.AlterField(
            model_name='mapmodelconfiguration',
            name='show_contour_lines',
            field=models.BooleanField(default=False, help_text='Afficher les isolignes de contour (contour)', verbose_name='Afficher les isolignes de contour'),
        ),
    ]
