# Generated by Django 5.1.8 on 2025-05-18 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0008_mapmodelconfiguration_contour_edgecolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='hauteur',
            field=models.FloatField(default=6.4, help_text='Hauteur de la carte (5.1 à 20.0 pouces)', validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(20.0)], verbose_name='Hauteur de la carte'),
        ),
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='largeur',
            field=models.FloatField(default=6.4, help_text='Largeur de la carte (5.1 à 20.0 pouces)', validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(20.0)], verbose_name='Largeur de la carte'),
        ),
    ]
