# Generated by Django 5.1.8 on 2025-05-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0009_mapmodelconfiguration_hauteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapfcstconfiguration',
            name='titre_carte',
            field=models.CharField(default='Titre de la carte', max_length=255),
        ),
        migrations.AlterField(
            model_name='mapfcstconfiguration',
            name='zip_file',
            field=models.FileField(help_text='Fichier ZIP contenant le shapefile.', upload_to='shapefiles/'),
        ),
        migrations.AlterField(
            model_name='mapobsconfiguration',
            name='titre_carte',
            field=models.CharField(default='Titre de la carte', max_length=255),
        ),
        migrations.AlterField(
            model_name='mapobsconfiguration',
            name='zip_file',
            field=models.FileField(help_text='Fichier ZIP contenant le shapefile.', upload_to='shapefiles/'),
        ),
    ]
