# Generated by Django 5.1.8 on 2025-05-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0010_alter_mapfcstconfiguration_titre_carte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the legend', max_length=150, unique=True)),
                ('active', models.BooleanField(default=True, help_text='Activate or disactivate the legend')),
                ('descriptions', models.JSONField(blank=True, default={'-1': {'color': '#6258a1', 'description': 'Class -1'}, '-10': {'color': '#5061af', 'description': 'Class -10'}, '-11': {'color': '#4e62b0', 'description': 'Class -11'}, '-12': {'color': '#4c63b2', 'description': 'Class -12'}, '-13': {'color': '#4a64b3', 'description': 'Class -13'}, '-14': {'color': '#4865b5', 'description': 'Class -14'}, '-15': {'color': '#4767b7', 'description': 'Class -15'}, '-2': {'color': '#6059a2', 'description': 'Class -2'}, '-3': {'color': '#5e5aa4', 'description': 'Class -3'}, '-4': {'color': '#5c5ba5', 'description': 'Class -4'}, '-5': {'color': '#5a5ca7', 'description': 'Class -5'}, '-6': {'color': '#585da9', 'description': 'Class -6'}, '-7': {'color': '#565eaa', 'description': 'Class -7'}, '-8': {'color': '#545fac', 'description': 'Class -8'}, '-9': {'color': '#5260ad', 'description': 'Class -9'}, '0': {'color': '#64579f', 'description': 'Class 0'}, '1': {'color': '#66559e', 'description': 'Class 1'}, '10': {'color': '#784c90', 'description': 'Class 10'}, '11': {'color': '#7a4b8e', 'description': 'Class 11'}, '12': {'color': '#7c4a8d', 'description': 'Class 12'}, '13': {'color': '#7e498b', 'description': 'Class 13'}, '14': {'color': '#80488a', 'description': 'Class 14'}, '15': {'color': '#824788', 'description': 'Class 15'}, '16': {'color': '#834586', 'description': 'Class 16'}, '17': {'color': '#854485', 'description': 'Class 17'}, '18': {'color': '#874383', 'description': 'Class 18'}, '19': {'color': '#894282', 'description': 'Class 19'}, '2': {'color': '#68549c', 'description': 'Class 2'}, '20': {'color': '#8b4180', 'description': 'Class 20'}, '21': {'color': '#8d407f', 'description': 'Class 21'}, '22': {'color': '#8f3f7d', 'description': 'Class 22'}, '23': {'color': '#913e7c', 'description': 'Class 23'}, '24': {'color': '#933d7a', 'description': 'Class 24'}, '25': {'color': '#953c79', 'description': 'Class 25'}, '26': {'color': '#973b77', 'description': 'Class 26'}, '27': {'color': '#993a75', 'description': 'Class 27'}, '28': {'color': '#9b3974', 'description': 'Class 28'}, '29': {'color': '#9d3872', 'description': 'Class 29'}, '3': {'color': '#6a539b', 'description': 'Class 3'}, '30': {'color': '#9f3771', 'description': 'Class 30'}, '31': {'color': '#a1356f', 'description': 'Class 31'}, '32': {'color': '#a3346e', 'description': 'Class 32'}, '33': {'color': '#a5336c', 'description': 'Class 33'}, '34': {'color': '#a7326b', 'description': 'Class 34'}, '35': {'color': '#a93169', 'description': 'Class 35'}, '36': {'color': '#ab3067', 'description': 'Class 36'}, '37': {'color': '#ad2f66', 'description': 'Class 37'}, '38': {'color': '#af2e64', 'description': 'Class 38'}, '39': {'color': '#b12d63', 'description': 'Class 39'}, '4': {'color': '#6c5299', 'description': 'Class 4'}, '40': {'color': '#b32c61', 'description': 'Class 40'}, '41': {'color': '#b52b60', 'description': 'Class 41'}, '42': {'color': '#b72a5e', 'description': 'Class 42'}, '43': {'color': '#b9295d', 'description': 'Class 43'}, '44': {'color': '#bb285b', 'description': 'Class 44'}, '5': {'color': '#6e5198', 'description': 'Class 5'}, '6': {'color': '#705096', 'description': 'Class 6'}, '7': {'color': '#724f94', 'description': 'Class 7'}, '8': {'color': '#744e93', 'description': 'Class 8'}, '9': {'color': '#764d91', 'description': 'Class 9'}}, help_text='The classes of the legend, their descriptions and their colors (python-dict or json-file)')),
            ],
            options={
                'permissions': [('edit_legends', 'Can edit legends')],
            },
        ),
    ]
