# Generated by Django 5.1.8 on 2025-05-22 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0011_legend'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='legend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legendMap', to='chartmet.legend', verbose_name='Légende Personnalisée'),
        ),
    ]
