# Generated by Django 5.1.8 on 2025-05-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0012_mapmodelconfiguration_legend'),
    ]

    operations = [
        migrations.AddField(
            model_name='legend',
            name='title',
            field=models.CharField(blank=True, help_text='titre affiché sur la carte', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='legend',
            name='name',
            field=models.CharField(help_text='Nom de la légende', max_length=150, unique=True),
        ),
    ]
