# Generated by Django 5.1.8 on 2025-05-23 04:44

import chartmet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0013_legend_title_alter_legend_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legend',
            name='descriptions',
            field=models.JSONField(blank=True, default=chartmet.models.default_descriptions, help_text='Classes, descriptions et couleurs (dict JSON)'),
        ),
    ]
