# Generated by Django 5.1.8 on 2025-05-24 11:02

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0014_alter_legend_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='couleur_symbole',
            field=colorfield.fields.ColorField(default='#000000', help_text='Couleur des symboles.', image_field=None, max_length=25, samples=None, verbose_name='Couleur des symboles'),
        ),
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='couleur_text',
            field=colorfield.fields.ColorField(default='#000000', help_text='Couleur des étiquettes.', image_field=None, max_length=25, samples=None, verbose_name='Couleur des étiquettes'),
        ),
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='symbole',
            field=models.CharField(choices=[('o', 'o'), ('.', '.'), (',', ','), ('x', 'x'), ('+', '+'), ('v', 'v'), ('^', '^'), ('<', '<'), ('>', '>'), ('s', 's'), ('p', 'p'), ('*', '*'), ('h', 'h'), ('H', 'H'), ('D', 'D'), ('d', 'd'), ('|', '|'), ('_', '_')], default='o', help_text='symbole utilisé pour représenter les localités', verbose_name='Symboles'),
        ),
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='symbole_size',
            field=models.PositiveIntegerField(default=5, help_text='Taille des symboles (3 à 20).', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)], verbose_name='Taille des symboles'),
        ),
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='text_labelsize',
            field=models.PositiveIntegerField(default=5, help_text='Taille de police des étiquettes (3 à 20).', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)], verbose_name='Taille de la police des étiquettes'),
        ),
    ]
