# Generated by Django 5.1.8 on 2025-05-24 12:24

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0015_mapmodelconfiguration_couleur_symbole_and_more'),
        ('observation', '0004_alter_station_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='couleur_symbole_station',
            field=colorfield.fields.ColorField(default='#000000', help_text='Couleur des symboles.', image_field=None, max_length=25, samples=None, verbose_name='Couleur des symboles'),
        ),
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='couleur_text_station',
            field=colorfield.fields.ColorField(default='#000000', help_text='Couleur des étiquettes.', image_field=None, max_length=25, samples=None, verbose_name='Couleur des étiquettes'),
        ),
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='stations',
            field=models.ManyToManyField(blank=True, help_text='Stations à afficher sur la carte', limit_choices_to={'active': True}, related_name='stations_map_configurations', to='observation.station', verbose_name='Stations affichées'),
        ),
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='symbole_size_station',
            field=models.PositiveIntegerField(default=1, help_text='Taille des symboles (1 à 20).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Taille des symboles'),
        ),
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='symbole_station',
            field=models.CharField(choices=[('o', 'o'), ('.', '.'), (',', ','), ('x', 'x'), ('+', '+'), ('v', 'v'), ('^', '^'), ('<', '<'), ('>', '>'), ('s', 's'), ('p', 'p'), ('*', '*'), ('h', 'h'), ('H', 'H'), ('D', 'D'), ('d', 'd'), ('|', '|'), ('_', '_')], default='o', help_text='symbole utilisé pour représenter les stations', verbose_name='Symboles stations'),
        ),
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='text_labelsize_station',
            field=models.PositiveIntegerField(default=3, help_text='Taille de police des étiquettes (3 à 20).', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)], verbose_name='Taille de la police des étiquettes'),
        ),
        migrations.AlterField(
            model_name='mapmodelconfiguration',
            name='symbole_size',
            field=models.PositiveIntegerField(default=1, help_text='Taille des symboles (1 à 20).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Taille des symboles'),
        ),
        migrations.AlterField(
            model_name='mapmodelconfiguration',
            name='text_labelsize',
            field=models.PositiveIntegerField(default=3, help_text='Taille de police des étiquettes (3 à 20).', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)], verbose_name='Taille de la police des étiquettes'),
        ),
    ]
