# Generated by Django 5.1.8 on 2025-05-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0016_mapmodelconfiguration_couleur_symbole_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='extrapolate',
            field=models.BooleanField(default=True, help_text="Activer l'extrapolatiin (Attention: il faut que l'interpolation soit désactivée", verbose_name='Extrapolation'),
        ),
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='extrapolation_method',
            field=models.CharField(choices=[('multiquadric', 'Multiquadrique'), ('inverse', 'Inverse'), ('gaussian', 'Gaussienne'), ('linear', 'Linéaire'), ('cubic', 'Cubique'), ('quintic', 'Quintique'), ('thin_plate', 'Plaque mince')], default='linear', verbose_name="Méthode d'extrapolation"),
        ),
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='interpolate',
            field=models.BooleanField(default=True, help_text="Activer l'interpolation", verbose_name='Interpolation'),
        ),
    ]
