# Generated by Django 5.1.8 on 2025-05-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0017_mapmodelconfiguration_extrapolate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapmodelconfiguration',
            name='extrapolate',
            field=models.BooleanField(default=False, help_text="Activer l'extrapolatiin (Attention: il faut que l'interpolation soit désactivée", verbose_name='Extrapolation'),
        ),
    ]
