# Generated by Django 5.1.8 on 2025-05-29 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0047_alter_bulletintemplate_content'),
        ('chartmet', '0019_mapspatialconfiguration'),
        ('forecast', '0013_remove_zone_unique_name_category_alter_zone_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapspatialconfiguration',
            name='echeance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EchMapSpa', to='bulletins.echeance', verbose_name='Echéance'),
        ),
        migrations.AlterField(
            model_name='mapspatialconfiguration',
            name='parametre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ParamMapSpa', to='forecast.variable', verbose_name='Paramètre'),
        ),
    ]
