# Generated by Django 5.1.8 on 2025-06-01 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0020_alter_mapspatialconfiguration_echeance_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapfcstconfiguration',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Logo ou icône à afficher sur la carte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='mapobsconfiguration',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Logo ou icône à afficher sur la carte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
