# Generated by Django 5.1.8 on 2025-06-01 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0021_mapfcstconfiguration_logo_mapobsconfiguration_logo'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Logo ou icône à afficher sur la carte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='mapspatialconfiguration',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Logo ou icône à afficher sur la carte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
