# Generated by Django 5.1.8 on 2025-06-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0022_mapmodelconfiguration_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapfcstconfiguration',
            name='zip_file',
            field=models.FileField(blank=True, help_text='Fichier ZIP contenant le shapefile.', null=True, upload_to='shapefiles/'),
        ),
        migrations.AlterField(
            model_name='mapobsconfiguration',
            name='zip_file',
            field=models.FileField(blank=True, help_text='Fichier ZIP contenant le shapefile.', null=True, upload_to='shapefiles/'),
        ),
    ]
