# Generated by Django 5.1.8 on 2025-06-01 22:00

import chartmet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0023_alter_mapfcstconfiguration_zip_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapmodelconfiguration',
            name='zip_file',
            field=models.FileField(blank=True, help_text='Fichier ZIP contenant le shapefile.', null=True, upload_to=chartmet.models.shapefile_upload_path, verbose_name='Fichier Shapefile (ZIP)'),
        ),
    ]
