# Generated by Django 5.1.8 on 2025-06-01 22:31

import chartmet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0024_alter_mapmodelconfiguration_zip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapspatialconfiguration',
            name='extrapolate',
            field=models.BooleanField(default=True, help_text="Activer l'extrapolatiin (Attention: il faut que l'interpolation soit désactivée", verbose_name='Extrapolation'),
        ),
        migrations.AlterField(
            model_name='mapspatialconfiguration',
            name='interpolate',
            field=models.BooleanField(default=False, help_text="Activer l'interpolation", verbose_name='Interpolation'),
        ),
        migrations.AlterField(
            model_name='mapspatialconfiguration',
            name='zip_file',
            field=models.FileField(blank=True, help_text='Fichier ZIP contenant le shapefile.', null=True, upload_to=chartmet.models.shapefile_upload_path, verbose_name='Fichier Shapefile (ZIP)'),
        ),
    ]
