# Generated by Django 5.1.8 on 2025-06-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0025_alter_mapspatialconfiguration_extrapolate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapfcstconfiguration',
            name='pluie',
            field=models.BooleanField(default=False, help_text='Afficher la Pluie'),
        ),
        migrations.AddField(
            model_name='mapfcstconfiguration',
            name='pression',
            field=models.BooleanField(default=False, help_text='Afficher la Pression'),
        ),
        migrations.AddField(
            model_name='mapfcstconfiguration',
            name='temps_sensible',
            field=models.BooleanField(default=True, help_text='Afficher les picto du Temps Sensible'),
        ),
        migrations.AddField(
            model_name='mapfcstconfiguration',
            name='tmax',
            field=models.BooleanField(default=True, help_text='Afficher les Tmax'),
        ),
        migrations.AddField(
            model_name='mapfcstconfiguration',
            name='tmin',
            field=models.BooleanField(default=True, help_text='Afficher les Tmin'),
        ),
        migrations.AddField(
            model_name='mapfcstconfiguration',
            name='vent',
            field=models.BooleanField(default=False, help_text='Afficher le Vent'),
        ),
        migrations.AddField(
            model_name='mapobsconfiguration',
            name='pluie',
            field=models.BooleanField(default=False, help_text='Afficher la Pluie'),
        ),
        migrations.AddField(
            model_name='mapobsconfiguration',
            name='pression',
            field=models.BooleanField(default=False, help_text='Afficher la Pression'),
        ),
        migrations.AddField(
            model_name='mapobsconfiguration',
            name='temps_sensible',
            field=models.BooleanField(default=True, help_text='Afficher les picto du Temps Sensible'),
        ),
        migrations.AddField(
            model_name='mapobsconfiguration',
            name='tmax',
            field=models.BooleanField(default=True, help_text='Afficher les Tmax'),
        ),
        migrations.AddField(
            model_name='mapobsconfiguration',
            name='tmin',
            field=models.BooleanField(default=True, help_text='Afficher les Tmin'),
        ),
        migrations.AddField(
            model_name='mapobsconfiguration',
            name='vent',
            field=models.BooleanField(default=False, help_text='Afficher le Vent'),
        ),
    ]
