# Generated by Django 5.1.8 on 2025-06-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0026_mapfcstconfiguration_pluie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='variogram_model',
            field=models.CharField(choices=[('spherical', 'Sphérique'), ('linear', 'Linéaire'), ('power', 'Puissance'), ('gaussian', 'Gaussien'), ('exponential', 'Exponentiel')], default='spherical', help_text='Choisir le variogramme Model seulement pour la méthode krigging', verbose_name='Variogram model utilisé'),
        ),
        migrations.AddField(
            model_name='mapspatialconfiguration',
            name='variogram_model',
            field=models.CharField(choices=[('spherical', 'Sphérique'), ('linear', 'Linéaire'), ('power', 'Puissance'), ('gaussian', 'Gaussien'), ('exponential', 'Exponentiel')], default='spherical', help_text='Choisir le variogramme Model seulement pour la méthode krigging', verbose_name='Variogram model utilisé'),
        ),
        migrations.AlterField(
            model_name='mapmodelconfiguration',
            name='extrapolation_method',
            field=models.CharField(choices=[('multiquadric', 'Multiquadrique'), ('kriging', 'kriging'), ('inverse', 'Inverse'), ('gaussian', 'Gaussienne'), ('linear', 'Linéaire'), ('cubic', 'Cubique'), ('quintic', 'Quintique'), ('thin_plate', 'Plaque mince')], default='linear', verbose_name="Méthode d'extrapolation"),
        ),
        migrations.AlterField(
            model_name='mapmodelconfiguration',
            name='interpolation_method',
            field=models.CharField(choices=[('linear', 'Linéaire'), ('nearest', 'Voisin le plus proche'), ('cubic', 'Cubique'), ('kriging', 'kriging')], default='linear', verbose_name="Méthode d'interpolation"),
        ),
        migrations.AlterField(
            model_name='mapspatialconfiguration',
            name='extrapolation_method',
            field=models.CharField(choices=[('multiquadric', 'Multiquadrique'), ('kriging', 'kriging'), ('inverse', 'Inverse'), ('gaussian', 'Gaussienne'), ('linear', 'Linéaire'), ('cubic', 'Cubique'), ('quintic', 'Quintique'), ('thin_plate', 'Plaque mince')], default='linear', verbose_name="Méthode d'extrapolation"),
        ),
        migrations.AlterField(
            model_name='mapspatialconfiguration',
            name='interpolation_method',
            field=models.CharField(choices=[('linear', 'Linéaire'), ('nearest', 'Voisin le plus proche'), ('cubic', 'Cubique'), ('kriging', 'kriging')], default='linear', verbose_name="Méthode d'interpolation"),
        ),
        migrations.AlterField(
            model_name='mapspatialconfiguration',
            name='source',
            field=models.CharField(choices=[('observation', 'Observation')], default='observation', help_text="Source d'observation", verbose_name='Source de données'),
        ),
    ]
