# Generated by Django 5.1.8 on 2025-06-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0027_mapmodelconfiguration_variogram_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapfcstconfiguration',
            name='titre_carte',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mapfcstconfiguration',
            name='titre_date',
            field=models.BooleanField(default=False, help_text='Afficher la date sous le titre.'),
        ),
        migrations.AlterField(
            model_name='mapmodelconfiguration',
            name='titre_carte',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre de la carte'),
        ),
        migrations.AlterField(
            model_name='mapmodelconfiguration',
            name='titre_date',
            field=models.BooleanField(default=False, help_text='Afficher la date sous le titre.', verbose_name='Afficher la date'),
        ),
        migrations.AlterField(
            model_name='mapobsconfiguration',
            name='titre_carte',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mapobsconfiguration',
            name='titre_date',
            field=models.BooleanField(default=False, help_text='Afficher la date sous le titre.'),
        ),
        migrations.AlterField(
            model_name='mapspatialconfiguration',
            name='titre_carte',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre de la carte'),
        ),
        migrations.AlterField(
            model_name='mapspatialconfiguration',
            name='titre_date',
            field=models.BooleanField(default=False, help_text='Afficher la date sous le titre.', verbose_name='Afficher la date'),
        ),
    ]
