# Generated by Django 5.1.8 on 2025-06-10 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0029_mapfcstconfiguration_legende_1_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapfcstconfiguration',
            name='legende_3',
            field=models.ForeignKey(blank=True, help_text='Légende à afficher dans la carte (en haut à droite)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='mapobsconfiguration',
            name='legende_3',
            field=models.ForeignKey(blank=True, help_text='Légende à afficher dans la carte (en haut à droite)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='mapfcstconfiguration',
            name='legende_1',
            field=models.ForeignKey(blank=True, help_text='Légende à afficher dans la carte (en haut à gauche)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='mapfcstconfiguration',
            name='legende_2',
            field=models.ForeignKey(blank=True, help_text='Légende à afficher dans la carte (en bas à droite)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='mapobsconfiguration',
            name='legende_1',
            field=models.ForeignKey(blank=True, help_text='Légende à afficher dans la carte (en haut à gauche)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='mapobsconfiguration',
            name='legende_2',
            field=models.ForeignKey(blank=True, help_text='Légende à afficher dans la carte (en bas à droite)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
