# Generated by Django 5.1.8 on 2025-06-10 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0030_mapfcstconfiguration_legende_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapfcstconfiguration',
            name='taille_legende_1',
            field=models.FloatField(default=5, help_text='Taille de la légende de 2% à 20%', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='mapfcstconfiguration',
            name='taille_legende_2',
            field=models.FloatField(default=5, help_text='Taille de la légende de 2% à 20%', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='mapfcstconfiguration',
            name='taille_legende_3',
            field=models.FloatField(default=5, help_text='Taille de la légende de 2% à 20%', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='mapobsconfiguration',
            name='taille_legende_1',
            field=models.FloatField(default=5, help_text='Taille de la légende de 2% à 20%', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='mapobsconfiguration',
            name='taille_legende_2',
            field=models.FloatField(default=5, help_text='Taille de la légende de 2% à 20%', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='mapobsconfiguration',
            name='taille_legende_3',
            field=models.FloatField(default=5, help_text='Taille de la légende de 2% à 20%', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
