# Generated by Django 5.1.8 on 2025-06-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0032_alter_mapfcstconfiguration_options_and_more'),
        ('observation', '0010_alter_climatdecades_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapobsconfiguration',
            name='stations',
            field=models.ManyToManyField(blank=True, help_text="Stations utilisées pour les cartes d'observation.", related_name='map_configurations', to='observation.station'),
        ),
    ]
