# Generated by Django 5.1.8 on 2025-06-19 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0033_alter_mapobsconfiguration_stations'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapfcstconfiguration',
            name='shapefile',
            field=models.ForeignKey(blank=True, help_text='Shapefile associer à la carte (.zip)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='mapobsconfiguration',
            name='shapefile',
            field=models.ForeignKey(blank=True, help_text='Shapefile associer à la carte (.zip)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
