# Generated by Django 5.1.8 on 2025-06-19 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0034_mapfcstconfiguration_shapefile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapfcstconfiguration',
            name='zip_file',
        ),
        migrations.RemoveField(
            model_name='mapobsconfiguration',
            name='zip_file',
        ),
    ]
