# Generated by Django 5.1.8 on 2025-06-19 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0035_remove_mapfcstconfiguration_zip_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapfcstconfiguration',
            old_name='shapefile',
            new_name='zip_file',
        ),
        migrations.RenameField(
            model_name='mapobsconfiguration',
            old_name='shapefile',
            new_name='zip_file',
        ),
    ]
