# Generated by Django 5.1.8 on 2025-06-19 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0037_alter_mapfcstconfiguration_zip_file_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapmodelconfiguration',
            name='zip_file',
            field=models.ForeignKey(blank=True, help_text='Shapefile associer à la carte (.zip)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='mapspatialconfiguration',
            name='zip_file',
            field=models.ForeignKey(blank=True, help_text='Shapefile associer à la carte (.zip)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtaildocs.document'),
        ),
    ]
