# Generated by Django 5.1.8 on 2025-06-19 06:05

import chartmet.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0038_alter_mapmodelconfiguration_zip_file_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='zip_file1',
            field=models.ForeignKey(blank=True, help_text='Shapefile associer à la carte (.zip)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='mapspatialconfiguration',
            name='zip_file1',
            field=models.ForeignKey(blank=True, help_text='Shapefile associer à la carte (.zip)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='mapmodelconfiguration',
            name='zip_file',
            field=models.FileField(blank=True, help_text='Fichier ZIP contenant le shapefile.', null=True, upload_to=chartmet.models.shapefile_upload_path, verbose_name='Fichier Shapefile (ZIP)'),
        ),
        migrations.AlterField(
            model_name='mapspatialconfiguration',
            name='zip_file',
            field=models.FileField(blank=True, help_text='Fichier ZIP contenant le shapefile.', null=True, upload_to=chartmet.models.shapefile_upload_path, verbose_name='Fichier Shapefile (ZIP)'),
        ),
    ]
