# Generated by Django 5.1.8 on 2025-06-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0039_mapmodelconfiguration_zip_file1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapmodelconfiguration',
            old_name='zip_file',
            new_name='zip_file2',
        ),
        migrations.RenameField(
            model_name='mapspatialconfiguration',
            old_name='zip_file',
            new_name='zip_file2',
        ),
    ]
