# Generated by Django 5.1.8 on 2025-06-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0040_rename_zip_file_mapmodelconfiguration_zip_file2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapmodelconfiguration',
            old_name='zip_file2',
            new_name='zip_file6',
        ),
        migrations.RenameField(
            model_name='mapmodelconfiguration',
            old_name='zip_file1',
            new_name='zip_file7',
        ),
        migrations.RenameField(
            model_name='mapspatialconfiguration',
            old_name='zip_file2',
            new_name='zip_file6',
        ),
        migrations.RenameField(
            model_name='mapspatialconfiguration',
            old_name='zip_file1',
            new_name='zip_file7',
        ),
    ]
