# Generated by Django 5.1.8 on 2025-06-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0041_rename_zip_file2_mapmodelconfiguration_zip_file6_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapmodelconfiguration',
            old_name='zip_file7',
            new_name='zip_file',
        ),
        migrations.RenameField(
            model_name='mapspatialconfiguration',
            old_name='zip_file7',
            new_name='zip_file',
        ),
        migrations.RemoveField(
            model_name='mapmodelconfiguration',
            name='zip_file6',
        ),
        migrations.RemoveField(
            model_name='mapspatialconfiguration',
            name='zip_file6',
        ),
    ]
