# Generated by Django 5.1.8 on 2025-08-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0042_rename_zip_file7_mapmodelconfiguration_zip_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='vario_nugget',
            field=models.FloatField(blank=True, help_text='Nugget : effet de pépite, valeur proche de 0', null=True, verbose_name='Nugget'),
        ),
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='vario_range',
            field=models.FloatField(blank=True, help_text='Range : portée du variogramme (distance maximale de corrélation)', null=True, verbose_name='Range'),
        ),
        migrations.AddField(
            model_name='mapmodelconfiguration',
            name='vario_sill',
            field=models.FloatField(blank=True, help_text='Sill : palier du variogramme (valeur maximale de la variance)', null=True, verbose_name='Sill'),
        ),
        migrations.AddField(
            model_name='mapspatialconfiguration',
            name='vario_nugget',
            field=models.FloatField(blank=True, help_text='Nugget : effet de pépite, valeur proche de 0', null=True, verbose_name='Nugget'),
        ),
        migrations.AddField(
            model_name='mapspatialconfiguration',
            name='vario_range',
            field=models.FloatField(blank=True, help_text='Range : portée du variogramme (distance maximale de corrélation)', null=True, verbose_name='Range'),
        ),
        migrations.AddField(
            model_name='mapspatialconfiguration',
            name='vario_sill',
            field=models.FloatField(blank=True, help_text='Sill : palier du variogramme (valeur maximale de la variance)', null=True, verbose_name='Sill'),
        ),
    ]
