# Generated by Django 5.1.8 on 2025-04-27 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image_path', models.CharField(max_length=255)),
                ('zoom', models.FloatField(default=1.0)),
                ('label', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherMapConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Conditions météo au Burkina Faso', max_length=200)),
                ('title_fontsize', models.IntegerField(default=14)),
                ('title_background_color', models.CharField(default='white', max_length=20)),
                ('title_padding', models.IntegerField(default=20)),
                ('background_color', models.CharField(default='white', max_length=20)),
                ('shapefile_path', models.CharField(max_length=255)),
                ('geojson_data_path', models.CharField(max_length=255)),
                ('longitude_min', models.FloatField(default=-6.0)),
                ('longitude_max', models.FloatField(default=3.0)),
                ('latitude_min', models.FloatField(default=9.0)),
                ('latitude_max', models.FloatField(default=15.0)),
                ('axis_visible', models.BooleanField(default=False)),
                ('save_path', models.CharField(default='burkina_weather_gray.png', max_length=255)),
                ('dpi', models.IntegerField(default=300)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherMapStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_fontsize', models.IntegerField(default=8)),
                ('city_box_color', models.CharField(default='white', max_length=20)),
                ('city_box_alpha', models.FloatField(default=0.7)),
                ('tmin_color', models.CharField(default='blue', max_length=20)),
                ('tmin_fontweight', models.CharField(default='bold', max_length=10)),
                ('tmin_fontsize', models.IntegerField(default=8)),
                ('tmax_color', models.CharField(default='red', max_length=20)),
                ('tmax_fontweight', models.CharField(default='bold', max_length=10)),
                ('tmax_fontsize', models.IntegerField(default=8)),
                ('separator_fontsize', models.IntegerField(default=8)),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='style', to='chartmet.weathermapconfig')),
            ],
        ),
        migrations.RemoveField(
            model_name='carteconfig',
            name='fond_image',
        ),
        migrations.RemoveField(
            model_name='carteconfig',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='carteconfig',
            name='shapefile_zone',
        ),
        migrations.DeleteModel(
            name='ParametreMeteo',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.DeleteModel(
            name='CarteConfig',
        ),
        migrations.DeleteModel(
            name='ShapefileZone',
        ),
    ]
