# Generated by Django 5.1.8 on 2025-04-27 12:46

import django.db.models.deletion
import wagtail_color_panel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0002_weathericon_weathermapconfig_weathermapstyle_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weathericon',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='weathermapconfig',
            name='geojson_data_path',
        ),
        migrations.RemoveField(
            model_name='weathermapconfig',
            name='shapefile_path',
        ),
        migrations.AddField(
            model_name='weathericon',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='weathermapconfig',
            name='geojson_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='weathermapconfig',
            name='shapefile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='weathermapconfig',
            name='background_color',
            field=wagtail_color_panel.fields.ColorField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='weathermapconfig',
            name='title_background_color',
            field=wagtail_color_panel.fields.ColorField(default='#ffffff', max_length=7),
        ),
        migrations.CreateModel(
            name='WeatherParameterStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=50)),
                ('color', wagtail_color_panel.fields.ColorField(default='#0000ff', max_length=7)),
                ('fontweight', models.CharField(choices=[('normal', 'Normal'), ('bold', 'Gras')], default='bold', max_length=10)),
                ('fontsize', models.IntegerField(default=8)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_styles', to='chartmet.weathermapconfig')),
            ],
        ),
        migrations.DeleteModel(
            name='WeatherMapStyle',
        ),
    ]
