# Generated by Django 5.1.8 on 2025-04-27 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0003_remove_weathericon_image_path_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weathericon',
            options={'verbose_name': 'Icône météo', 'verbose_name_plural': 'Icônes météo'},
        ),
        migrations.AlterModelOptions(
            name='weathermapconfig',
            options={'verbose_name': 'Configuration carte', 'verbose_name_plural': 'Configurations cartes'},
        ),
        migrations.AlterModelOptions(
            name='weatherparameterstyle',
            options={'verbose_name': 'Style paramètre', 'verbose_name_plural': 'Styles paramètres'},
        ),
    ]
