# Generated by Django 5.1.8 on 2025-04-28 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0004_alter_weathericon_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weathericon',
            options={},
        ),
        migrations.AlterModelOptions(
            name='weathermapconfig',
            options={},
        ),
        migrations.AlterModelOptions(
            name='weatherparameterstyle',
            options={},
        ),
    ]
