# Generated by Django 5.1.8 on 2025-05-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0007_mapfcstconfiguration_mapobsconfiguration_and_more'),
        ('forecast', '0010_remove_observation_forecast_ptr_delete_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapfcstconfiguration',
            name='zones',
            field=models.ManyToManyField(blank=True, help_text='Zones utilisées pour les cartes de type prévision.', limit_choices_to={'category': 'ville'}, related_name='map_configurations', to='forecast.zone'),
        ),
    ]
