# Generated by Django 5.1.8 on 2025-05-08 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0008_alter_mapfcstconfiguration_zones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapfcstconfiguration',
            name='min_dist',
            field=models.FloatField(default=50, help_text='Distance minimale entre étiquettes (10 à 300km).', validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(300.0)]),
        ),
        migrations.AlterField(
            model_name='mapobsconfiguration',
            name='min_dist',
            field=models.FloatField(default=50, help_text='Distance minimale entre étiquettes (10 à 300km).', validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(300.0)]),
        ),
    ]
