# Generated by Django 5.1.8 on 2025-05-08 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0009_remove_mapobsconfiguration_type_map_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='mapobsconfiguration',
        #     name='type_map',
        # ),
    ]
