# Generated by Django 5.1.8 on 2025-05-08 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0010_remove_mapobsconfiguration_type_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapobsconfiguration',
            name='type_map',
        ),
    ]
