# Generated by Django 5.1.8 on 2025-06-18 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0031_mapfcstconfiguration_taille_legende_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapfcstconfiguration',
            options={'permissions': [('edit_mapfcst', 'Can edit Map Forecast')]},
        ),
        migrations.AlterModelOptions(
            name='mapmodelconfiguration',
            options={'permissions': [('edit_mapmodel', 'Can edit Map Model')]},
        ),
        migrations.AlterModelOptions(
            name='mapobsconfiguration',
            options={'permissions': [('edit_mapobs', 'Can edit Map Observation')]},
        ),
        migrations.AlterModelOptions(
            name='mapspatialconfiguration',
            options={'permissions': [('edit_mapspatial', 'Can edit Map Spacialised')]},
        ),
    ]
