# Generated by Django 5.1.8 on 2025-06-18 14:54

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0032_alter_mapfcstconfiguration_options_and_more'),
        ('observation', '0010_alter_climatdecades_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapobsconfiguration',
            name='stations',
        ),
        migrations.AddField(
            model_name='mapobsconfiguration',
            name='station',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='map_configs', to='observation.station', verbose_name='Stations associées'),
        ),
    ]
