# Generated by Django 5.1.8 on 2025-06-18 14:55

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartmet', '0033_remove_mapobsconfiguration_stations_and_more'),
        ('observation', '0010_alter_climatdecades_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapobsconfiguration',
            name='station',
        ),
        migrations.AddField(
            model_name='mapobsconfiguration',
            name='stations',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='map_configs', to='observation.station', verbose_name='Stations associées'),
        ),
    ]
